plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman

title: Khaki HubSpot Theme Documentation
show_downloads: false
